#!/bin/sh
. /lib/functions.sh
. /lib/functions/network.sh
. /lib/xq-misc/phy_switch.sh

export LANG=C
usage(){
	echo "USAGE: $0 [timeout] [WAN] [pppoe dhcp|pppoe|dhcp]"
}

timeout="$1"
test -z "$timeout" && timeout=2
let timeout=$timeout+1-1 2>/dev/null
test $? -ne 0 -a "$timeout" != '0' && timeout=2
test $timeout -le 0 && timeout=2

nic="$2"
[ $nic == "WAN" ] && nic="wan"
nic="${nic:-wan}"

if [ "$nic" != "wan" ]; then
    realnic=$nic
    cat /sys/class/net/$realnic/carrier | grep -q 1
    if [ $? -eq 0 ]; then
        echo "LINK=YES"
    else
        echo "LINK=NO"
        exit 0
    fi

else
    network_get_physdev realnic "$nic"
    realnic="${realnic:-eth0.2}"
    if sw_wan_link_detect; then
        echo "LINK=YES"
    else
        echo "LINK=NO"
        exit 0
    fi
fi

tobedetect="$3 $4"
[ "$tobedetect" = ' ' ] && tobedetect='pppoe dhcp'

for oncheck in $tobedetect
do
	case "$oncheck" in
		pppoe|PPPOE)
			#check PPPOE
 			hard_mode=$(uci -q get misc.hardware.model)
			[ -n "$hard_mode" -a $hard_mode == "R3D" ] && ifconfig eth0 promisc >/dev/null 2>&1
			runt $timeout /usr/sbin/pppoe-discovery -I $realnic >/dev/null 2>&1
			[ $? -eq 0 ] &&	echo "PPPOE=YES" ||	echo "PPPOE=NO"
			[ -n "$hard_mode" -a $hard_mode == "R3D" ] &&  ifconfig eth0 -promisc >/dev/null 2>&1
			;;
		dhcp|DHCP)
			#check dhcp
			udhcpc -B -C -n -q -s /bin/true -t 1 -T $timeout -i $realnic >/dev/null 2>&1
			if [ $? -eq 0 ]; then
				echo "DHCP=YES"
			else
				ubus call network.interface.wan down
				udhcpc -B -C -n -q -s /bin/true -t 1 -T $timeout -i $realnic >/dev/null 2>&1
				[ $? -eq 0 ] && echo "DHCP=YES" || echo "DHCP=NO"
				ubus call network.interface.wan up
			fi
			;;
		*)
			echo "$oncheck=UNKNOW"
			;;
	esac
done
exit 0
#
