#!/bin/sh

ft_mode=$(cat /proc/xiaoqiang/ft_mode)
[ "$BUTTON" = "reset" ] && {
	[ "1" = "$ft_mode" ] && {
		echo -e "BUTTON:$BUTTON ACTION:$ACTION SEEN:$SEEN\n" | tee /dev/console /dev/pts/* /tmp/button_test_$BUTTON.log
		exit 0
	}

	[ "$ACTION" = "reset" ] && {
		uptime
		xqled sys_booting;xqled func_off
		echo "Reset key is reset" | tee /dev/console
		ap_mode=$(uci -q get xiaoqiang.common.NETMODE)
		mesh_version=$(uci -q get xiaoqiang.common.MESH_VERSION)
		cap_mode=$(uci -q get xiaoqiang.common.CAP_MODE)
		if [ "$ap_mode" = "whc_cap" ] || [ "$mesh_version" = "2" -a "$ap_mode" = "lanapmode" -a "$cap_mode" = "ap" ]; then
			ubus call xq_info_sync_mqtt restore
		fi
	}
}
